### ISSUE TITLE
vanella script last few lines

### ISSUE THREAD

**Issue by atticus-sullivan** [addy-dclxvi/void-bspwm-dotfiles#4]
Hi,

I just found your config files and thought I would use them to smoothen my transition to bspwm (this way I don't have to start from scratch). While reading your script for the statusbar (vanela) I got a bit confused what you're doing in the end. (I have to admit that I've never worked with fifos that much in bash scripting). You're running all the commands which pipe something into the fifo in parallel and pipe the content of the fifo indirectly (over panel_bar) to lemonbar (I guess the `| bash` is for the actions when clicking on the bar).

But then somehow you're inputting "dummy" into the fifo to refresh instantaneously when reloading??? (how's that supposed to refresh the bar?) And isn't that executed right after initializing the bar (because of the `&` after the line with the many pipes)?

And isn't the part for fullscreen only supposed to be executed when switching to fullscreen (in my opinion it is executed once in the beginning)?

So the first part I totally understand (at least I think so), but the part after line 208 is totally unclear to me, I would be glad if you could elaborate on this ;)

**Comment by addy-dclxvi** [comment]
Hi,

I'm not a programmer or any IT related guy, so my priority is "just work" despite the script is very hacky and not elegant.

> You're running all the commands which pipe something into the fifo in parallel and pipe the content of the fifo indirectly (over panel_bar) to lemonbar (I guess the | bash is for the actions when clicking on the bar).

Yes, fifo make it possible to refresh the statusline items in different interval (not all items needs to be refreshed every second).

![old-bspwm](https://raw.githubusercontent.com/addy-dclxvi/almighty-dotfiles/master/preview-bspwm2.jpg)

(My old Lemonbar) Music status might be need to be refreshed every 2 seconds, but also refreshing battery status and clock every 2 seconds is not efficient. FIFO makes it possible to refresh the battery status & clock every 30 seconds while keeping my music status & network status refreshed every 2 seconds.

Yes the `| bash` is neccessary because lemonbar has a weird click action. Instead of `exec <command>`, it does `echo <command>`. So, in order to make the click command executed, it need to be sent to the shell (`echo <command> | bash`).

> But then somehow you're inputting "dummy" into the fifo to refresh instantaneously when reloading??? (how's that supposed to refresh the bar?) And isn't that executed right after initializing the bar (because of the & after the line with the many pipes)?

I also found other weirdness. When I reload the bspwmrc (by executing ~/.config/bspwm/bspwmrc). Some items in the statusbar is not reloaded (I also cannot figure out why) until something in the FIFO changed. So, the cheap solution is to echo something/anything to the FIFO.

> And isn't the part for fullscreen only supposed to be executed when switching to fullscreen (in my opinion it is executed once in the beginning)?

It's a rule for xdo (window arranger/manipulator). And the rule is only need to be set up once. It just like asking "xdo please listen. Currently when I set the window to fullscreen/monocle/`bspc desktop -l next`, my panel is covering the top of my fullscreen window. I want to make my panel not visible when I set my window to fullscreen. I only need to ask you once, then do the same forever".

I hope it's understandable. despite of my poor explanation, especially because english is not my native languange (hard to express my mind).

And keep exploring. Bspwm is very cool.

**Comment by atticus-sullivan** [comment]
> Music status might be need to be refreshed every 2 seconds, but also refreshing battery status and clock every 2 seconds is not efficient. FIFO makes it possible to refresh the battery status & clock every 30 seconds while keeping my music status & network status refreshed every 2 seconds.

Actually I was just looking for something like this (even though I thought I'd have to use a program like dwmblocks or something else which manages this (only thing I'll have to do now is to make "blocks" only update when receiving a signal (shouldn't be a problem but I'll have to look up how to handle signals inside of functions)))

> Yes the | bash is neccessary because lemonbar has a weird click action. Instead of exec <command>, it does echo <command>. So, in order to make the click command executed, it need to be sent to the shell (echo <command> | bash).

Ok good to know, thanks (thought I read this somewhere but couldn't find it yesterday)

> I also found other weirdness.

Which ones else with bspwm/lemonbar (I think this would be good to know)?

> When I reload the bspwmrc (by executing ~/.config/bspwm/bspwmrc). Some items in the statusbar is not reloaded (I also cannot figure out why) until something in the FIFO changed. So, the cheap solution is to echo something/anything to the FIFO.

So this definitely is weird, but this is something, if you know it, you don't care.

> It's a rule for xdo (window arranger/manipulator). And the rule is only need to be set up once. It just like asking "xdo please listen. Currently when I set the window to fullscreen/monocle/bspc desktop -l next, my panel is covering the top of my fullscreen window. I want to make my panel not visible when I set my window to fullscreen. I only need to ask you once, then do the same forever".

Ok I understand what you're doing, but I don't see why the rule does only apply when being in monocle/fullscreen mode, why is the bar not below the windows in the normal tiling mode?

> I hope it's understandable. despite of my poor explanation, especially because english is not my native languange (hard to express my mind).

Don't be afraid, if someone cannot understand you, he is supposed to ask about the parts he didn't get (that's why this is interactive ;) (and English isn't my first language as well)

> And keep exploring. Bspwm is very cool.

Yea coming from dwm, it's pretty amazing how easy it is to modify something. (no one can tell me, that C is easier than bash ^^)

Oh and I wasn't able to find something on this so maybe you know this one: What's the difference between the tiled and the pseudotiled mode in bspwm?
